name: Build

on:
  push:
    branches:
      - development
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"
        
      - name: Yarn Install
        run: yarn install
        
      - name: Build
        run: yarn utils:build

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: pr
          path: static

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:
