name: Build

on:
  push:
    branches:
      - development
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"
        
      - name: Yarn Install
        run: yarn install
        
      - name: Build
        run: yarn utils:build

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: pr
          path: static

      - name: Create a file with PR number
        run: echo -n ${{ github.event.number }} > pr-num.txt

      - name: Upload the PR number
        uses: actions/upload-artifact@v2
        with:
          name: pr-num
          path: pr-num.txt
